### ISSUE TITLE
HTTP ERROR 500 after automatic installation

### ISSUE THREAD

**Issue by rolero** [itconsultis/woocommerce-yoopay#1]
My website is not accessible anymore after installing the plugin using the automatic installation plugin procedure. Even WP-admin is not accessible anymore.

![image](https://user-images.githubusercontent.com/2805313/27847589-0825f2a6-6171-11e7-865e-efd98a085a0c.png)

Error log Apache:

[Tue Jul 04 22:55:59.024836 2017] [:error] [pid 24057] [client 69.167.26.121:43910] PHP Fatal error:  Declaration of Logger::error() must be compatible with WC_Logger_Interface::error($message, $context = Array) in **************l/wp-content/plugins/yoopay-woocommerce-gateway/WC_Gateway_Yoopay.php on line 42

After deleting the plugin folder on the server manually the website runs again.

Using:
WordPress 4.8
WooCommerce 3.1.0

**Comment by tguillemaud** [comment]
Hi @rolero 

This plugin is not actively maintained and has not been tested for Woocommerce 3.X. First fix would be to remove the module folder from wp-content/wp-plugins.

Feel free to contribute to the module on this repo if you wish to make it compatible with newer versions.

**Comment by gityoopay** [comment]
Hi @rolero,

We'd like you to know that the plugin has been updated to support the latest v4.9.

Please try it out and let us know if you have any further question.

Thank you,
Yoopay
